### ISSUE TITLE
Update breaks ghata

### ISSUE THREAD

**Issue by kesenwang** [vasanthdeveloper/ghata#19]
Hey there, love the plugin, I just have a couple questions. As well just heads up that Ghata prevented me essentially from upgrading saying it couldn't locate Ghata. I'm assuming this is because its symlinked to a different location other then in storage/adapters? Under node_modules right?

My question is concerning image resizing. Does this in any way disable image resizing by ghost? I know that the Cloudinary adapter will be default stop resizing of images, but for some reason since Ghata my images have stopped resizing.

Thanks!

**Comment by vasanthdeveloper** [comment]
> As well just heads up that Ghata prevented me essentially from upgrading saying it couldn't locate Ghata.

Can you please elaborate on this ☝️, is it upgrading `ghata` or Ghost? 🤔

> Does this in any way disable image resizing by ghost?

**Yes**, it's up to the storage adapter to manipulate images, and currently `ghata` doesn't support that. A PR is welcome if you would like to contribute.

PS: sorry for delayed response, I was working on a secret project 😉

**Comment by kesenwang** [comment]
Hahah no worries there, I’m not a seasoned developer or anything so there’s probably nothing I can contribute except probably for a little improving on the instructions, but your solution has been a godsend. Cloudinary was not a good option, this is cheap and works great.

It was just a matter of updating and then either copying and pasting the code or running Ghata again and just making sure it’s the same path as all the img src are still in tact.

Can’t wait to see your next project!!

**Comment by vasanthdeveloper** [comment]
Currently, I am working on my next video.
So, do check out my YouTube channel 👇
https://youtube.com/vasanthdeveloper

**Comment by kesenwang** [comment]
For some reason the edit button is not responding on my phone, but just so I’m understanding correctly, with Ghata as a storage adapter images won’t resize is that correct? 

I’m not able to create code or anything but I’m guessing there is some workaround like just resizing the images before upload? I’m going to look into it and just probably resize the images locally to the ghost standard sizing, but then I wouldn’t really know how to reference the new sizes and use media to choose which ones to use haha.

Anyways; awesome job!

**Comment by kesenwang** [comment]
I will check it out for sure! Just subscribed!

**Comment by vasanthdeveloper** [comment]
> with Ghata as a storage adapter images won’t resize is that correct?

Yes, that's correct.
